# Generated by Django 6.0.2 on 2026-02-04 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dictionary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "prompt",
                    models.TextField(
                        help_text="Prompt used for AI word generation, for example: 'vocabulary words related to cooking at beginner level'"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "dictionaries",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("word", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                ("definition", models.TextField()),
                ("example_sentence", models.TextField(blank=True)),
                ("pronunciation", models.CharField(blank=True, max_length=255)),
                ("part_of_speech", models.CharField(blank=True, max_length=50)),
                (
                    "dictionary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words",
                        to="dailyword.dictionary",
                    ),
                ),
            ],
            options={
                "ordering": ["word"],
                "abstract": False,
                "unique_together": {("dictionary", "slug")},
            },
        ),
    ]
