# Generated by Django 6.0.2 on 2026-02-04 15:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dailyword", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="word",
            unique_together={("dictionary", "word")},
        ),
        migrations.RemoveField(
            model_name="word",
            name="slug",
        ),
    ]
